spring:
  redis:
    database: 0     # Redis数据库索引 默认为 0
    host: 192.168.4.108
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
    timeout: 2000ms     # 连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.180.133:3306/summer?useSSL=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  session:
    store-type: none
  thymeleaf:
    cache: false
